apiVersion: v1
kind: Service
metadata:
  name: app-java
  labels:
    app: app-java
spec:
  type: LoadBalancer
  selector:
    app: app-java
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
