---
- name: Deploy app_java
  hosts: all
  become: true
  roles:
    - web_app
  vars:
    web_app_name: app_java
    web_app_internal_port: 8000
    web_app_external_port: 8000
    web_app_full_wipe: true
