apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: python.dmfrpro.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-python
            port:
              number: 8080
  - host: java.dmfrpro.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-java
            port:
              number: 8080
